spring:
  datasource:
    url: jdbc:mysql://db:3306/azan_kz?characterEncoding=UTF-8
    username: ${db-username}
    password: ${db-password}
  flyway:
    baseline-on-migrate: true
  output:
    ansi.enabled: ALWAYS

app:
  jwt:
    key: ${jwt-key}

server:
  servlet:
    context-path: /v1
